from .pigment_network import compute as compute_pigment_network
from .lacunae import compute as compute_lacunae
from .central_white_patch import compute as compute_central_white_patch
from .symmetry import compute as compute_symmetry
from .color_variegation import compute as compute_color_variegation
from .blue_white_veil import compute as compute_blue_white_veil
from .streaks import compute as compute_streaks
from .dots_globules import compute as compute_dots_globules
from .regression import compute as compute_regression
from .vascular_pattern import compute as compute_vascular_pattern
from .milia_cysts import compute as compute_milia_cysts
from .comedo_openings import compute as compute_comedo_openings
from .fissures_ridges import compute as compute_fissures_ridges
from .border_sharpness import compute as compute_border_sharpness
from .strawberry_pattern import compute as compute_strawberry_pattern
from .surface_texture import compute as compute_surface_texture
from .arborizing_vessels import compute as compute_arborizing_vessels
from .ovoid_nests import compute as compute_ovoid_nests
from .leaf_spoke_structures import compute as compute_leaf_spoke_structures